{
	"data": "ENC[AES256_GCM,data:kA4+N3OXHViYWp4m3NxnAI7WML+20udlcsZehJFxs+k54g19Qy8Mt3ubcBQa6rLDOZ7GRpPcGKjbWwtITG6PkTY4Iy15aUnaYudzo/f2wVWLdmKkhwc2ZhqQp89r/Xnl0dCdt0FMIQE78c8jXR/hlpw6k2fKK9RaYpFoVk9CQVvQkquLlHPOtuNvi2F3VbR7RPYmJAypqEkBB4anQ/kZpuZvSFBNpOytW7IFXKJYkyHYn69t9BuOjCC8jhkZq/NAFXbrE74mvmBOFxqBSE9MrB+VxTUS+lRuSj7iPI8BiI1UairBGl/ZYp5sxToR6XJmntxgEwf3JLcTP+F58f4m3ILSLgMo33V1aw0CaqoaIJik0M2Yj6XxwwTyhfZf3RPq8V/Xi+ybtx3/uTI75xXjy9sxBC9wApdQrqcx4b1NQwrAhBidBOQW5nOxmBdrzh3z3KrIEQSiMql0eHJ7R53OEBStKfjQeUSiHhXnq0maxm9c0MwYMkiaSFad37gmrJDUBHpYooQdkL3tQLixcK25ZIYj8XUqq0k1jSMtIMfWjJbiq1352fosS1fgPe3Jd8Sl3mkuTgJV5am4Tmctr/bQKheS8Xh6SlgojfGBX+EruA==,iv:BNBowzTPwxm6mmuAq/1mVFdv8UX/VzQcNQbxhQ6SkTM=,tag:9w+IvoXS+Qf55geBYKw5YA==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": [
			{
				"vault_address": "https://vault.cw.iog.io",
				"engine_path": "sops",
				"key_name": "ops",
				"created_at": "2022-09-02T14:42:31Z",
				"enc": "vault:v1:1V1rJJ8Hb07ZtlAfkwdPfMkTo7N0De8KmJiJjzg8rjo+rM9fQs30gxbGFqSkBSXJbZHnUhVkg19iw3Z2"
			}
		],
		"age": null,
		"lastmodified": "2022-09-02T14:42:37Z",
		"mac": "ENC[AES256_GCM,data:NRrLUBKc8uIyHksO3A2dPvrM8ZL6Jn8fbJRuXSPfHEivzh/r33uuSIb4Ypkqtratf0Ct82HdiptLv4l8AiPssPLXfFUn8B4qWppoWskqJ6Sg2TMNHZqAzd19+mOW2wAU/GIGtQQOniB4A6kxIZ50nHky4s8Ftvm0/N+yy2SQ//4=,iv:565Lf+tafE/A8q1fNVWN/LGS2Uxw3k+3LM5c7K59b2U=,tag:xixuqIy5AM/9lnrt8tN3sg==,type:str]",
		"pgp": null,
		"unencrypted_suffix": "_unencrypted",
		"version": "3.7.1"
	}
}